### ISSUE TITLE
Comp-3 function

### ISSUE THREAD

**Issue by mlbelobraydi** [mlbelobraydi/TXRRC_data_harvest#12]
**Is your feature request related to a problem? Please describe.**
The production data has several fields that are comp-3

**Describe the solution you'd like**
The positions in bytes are less than the ending number of digits. The pic_signed function does not account for this and an additional function needs to be created

**Describe alternatives you've considered**
Tried to find a way to modify pic_signed and it isn't possible and will require a new function for comp-3

**Additional context**
Information on Comp-3 can be found here
http://www.3480-3590-data-conversion.com/article-packed-fields.html

**Comment by mlbelobraydi** [comment]
Does this fix pic_V999

**Comment by mlbelobraydi** [comment]
Reviewing work completed by @skylerbast in [Cobol_types](https://github.com/skylerbast/TxRRC_data/blob/master/cobol_types.py) Comp3 function,  the pic_signed function should be able to handle this request. Unknown how it unpacks the fields to create the correct decimal places.

**Comment by skylerbast** [comment]
You are referring to the Gas or Oil Production ledgers such as the ones described [here](https://www.rrc.state.tx.us/media/1273/ola013k.pdf), right? Unfortunately the `pic_signed` function won't work, we'll have to add a new one to handle COMP-3. The function you referred to in my repo should work with minimal modification. I'll make a PR and add it shortly.

The reason the `pic_signed` function doesn't work is because the "signed" data items aren't compressed like the COMP-3 ones are; the signed numbers are stored as the EBCDIC representation of the numerals and the sign is overpunched (1,234 would be stored as `0xF1F2F3C4`, and -1,234 would be stored as `0xF1F2F3C4` for example). Therefore, to hold an <img src="https://render.githubusercontent.com/render/math?math=n"> digit number, the signed field must be <img src="https://render.githubusercontent.com/render/math?math=n"> bytes in size. So there's a small bit of space saved by overpunching the sign, but nothing huge. By contrast, COMP-3 numbers store the digits as their decimal values (rather than the code representing the digit's _numeral_), and adds a nibble at the end to represent the sign (1,234 would be stored as `0x01234C` and -1,234 would be stored as `0x01234D`). To store an <img src="https://render.githubusercontent.com/render/math?math=n"> digit number, the COMP-3 format requires <img src="https://render.githubusercontent.com/render/math?math=\left\lceil{\frac{n%2B1}{2}}\right\rceil "> bytes.

**Comment by mlbelobraydi** [comment]
Started new branch to try and solve the addition of comp3
